# Site settings
title: Sharon Saronian
description: Sharon Saronian's Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
plugins: - jekyll-seo-tag

# User settings
username: Sharon Saronian
user_description: I'm a machine learning engineer, based in Tehran, Iran. Currently, I work for Tosan company (www.tosan.com) where I build applications based on fintech and powered by AI.
user_title: Machine Learning Engineer
email: sh.saronian.ss@gmail.com
twitter_username: shsaronian
linkedin_username: sharon-saronian
github_username:  shsaronian


exclude: ['package.json', 'src' , 'node_modules']
