# Site settings
title: Sharon Saronian
tagline: Webpage where I showcase my resume
description: Sharon Saronian's Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
google-site-verification: OjuLR5zK9aXzmjhlPa0mFHrSL7Yc-TtRyRMoZEBvLGE
plugins:
  - jekyll-seo-tag

# User settings
username: Sharon Saronian
user_description: I'm a machine learning engineer, based in Tehran, Iran. Currently, I work for Tosan company (www.tosan.com) where I build applications based on fintech and powered by AI.
user_title: Machine Learning Engineer
email: sh.saronian.ss@gmail.com
twitter_username: Shsaronian
linkedin_username: sharon-saronian
github_username:  shsaronian

social:
  name: Sharon Saronian
  links:
    - https://twitter.com/Shsaronian
    - https://www.linkedin.com/in/sharon-saronian
    - https://github.com/shsaronian

author:
  twitter: Shsaronian

exclude: ['package.json', 'src' , 'node_modules']
